steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/teraform-project-401705/cloud-helm-deploy', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/teraform-project-401705/cloud-helm-deploy']
images:
  - 'us-central1-docker.pkg.dev/teraform-project-401705/cloud-helm-deploy'
