steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/teraform-project-401705/my-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/teraform-project-401705/my-app']
images:
  - 'gcr.io/teraform-project-401705/my-app'
