replicaCount: 1
workloadName: prod-application
image:
  repository: gcr.io/teraform-project-401705/image@sha256:2b8afd21d71332e89ee56fc2bed329bb1688615607342cd2ab9d23ac7838990e
  tag: latest
  pullPolicy: IfNotPresent
monitoring: false
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 128Mi
service:
  type: LoadBalancer
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
