replicaCount: 1
workloadName: prod-application
image:
  repository: gcr.io/teraform-project-401705/image
  tag: latest
  pullPolicy: Always
monitoring: false
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 128Mi
service:
  type: LoadBalancer
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
